---
title: "2025 HCTF Sampling Proposals"
author: "Chris Madsen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{css, echo = FALSE}
.leaflet-ENV_sampling_points-pane {
  width: 10rem !important;
  height: 10rem !important;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(sf)
library(leaflet)
library(bcdata)
```

```{r load_data}
dat_sf = sf::read_sf("data/2025_sampling_locations.gpkg")

# Some folks have retracted sampling applications. Remove them from the pool here.
dat_sf = dat_sf |> 
  dplyr::filter(!Group %in% c("LRISS"))

# Transform some sampling location names so that they match with
# the names in the freshwater atlas.
dat_sf = dat_sf |> 
  dplyr::mutate(waterbody_name = dplyr::case_when(
   waterbody_name == 'Arrow Lake, Upper' ~ "Upper Arrow Lake",
   waterbody_name == 'Arrow Lake, Lower' ~ "Lower Arrow Lake",
   stringr::str_detect(waterbody_name, 'Kootenay River') ~ "Kootenay River",
   T ~ waterbody_name
  ))

all_shortlist_lakes = sf::read_sf("W:/CMadsen/Projects/ZQMussels/2025 IMDP Final Report/data/spatial/waterbodies_zqm_shortlist_risk_estimates.gpkg") |> 
  sf::st_transform(4326)

menv_sampling = sf::read_sf("data/ministry_of_env_sampling.gpkg")

proposed_wb_names = unique(dat_sf$waterbody_name)
shortlist_wb_names = unique(all_shortlist_lakes$GNIS_NA)

dat_sf = dat_sf |> 
  dplyr::mutate(waterbody_is_on_priority_list = waterbody_name %in% shortlist_wb_names)

all_shortlist_lakes = all_shortlist_lakes |> 
  dplyr::mutate(proposed_sampling = ifelse(GNIS_NA %in% proposed_wb_names,"Sampling Proposed","No Sampling Proposed"))

# simplify lake geometries a bit.
all_shortlist_lakes_s = sf::st_simplify(all_shortlist_lakes, dTolerance = 20)

all_shortlist_lakes_w_props = all_shortlist_lakes_s |> dplyr::filter(proposed_sampling == "Sampling Proposed")
all_shortlist_lakes_wout_props = all_shortlist_lakes_s |> dplyr::filter(proposed_sampling != "Sampling Proposed")
```

```{r drop_samplers_who_have_retracted_application}

```

```{r get_parks}
if(!file.exists('data/all_bc_parks_simplified.gpkg')){
  all_bc_parks = bcdata::bcdc_query_geodata('bc-parks-ecological-reserves-and-protected-areas') |> 
    collect() |> 
    sf::st_transform(4326)
  
  sf::write_sf(all_bc_parks, "data/all_bc_parks.gpkg")
  
  all_bc_parks_s = rmapshaper::ms_simplify(all_bc_parks)
  
  sf::write_sf(all_bc_parks_s, "data/all_bc_parks_simplified.gpkg")
  
  bc_parks = all_bc_parks_s
  rm(all_bc_parks); rm(all_bc_parks_s)
} else {
  bc_parks = sf::read_sf('data/all_bc_parks_simplified.gpkg')
}
```

#### Priority Waterbodies without Proposals that Overlap with MENV sampling sites
```{r run_overlap}
# run_overlap_of_priority_wbs_without_hctf_proposals_and_env_sampling_sites
all_shortlist_lakes_wout_props |> 
  sf::st_filter(menv_sampling) |> 
  sf::st_drop_geometry() |> 
  DT::datatable()
```

## Interactive Map

```{r}
# Create interactive map.
my_pal = leaflet::colorFactor(palette = "Set3", domain = unique(dat_sf$Group))

props_pal = leaflet::colorFactor(palette = c("purple","orange"), domain = unique(all_shortlist_lakes_s$proposed_sampling))

dat_sf_tbls = leafpop::popupTable(
  dat_sf |> 
    sf::st_drop_geometry() |> 
    dplyr::select(-does_the_proposed_sampling_frequency_differ_from_current_priority_list) |> 
    dplyr::mutate(dplyr::across(c(on_last_years_priority_waterbody_list,sampled_last_year,substrate_sampler_planned), \(x) ifelse(x == "Y", "Yes", "No"))) |> 
    # dplyr::mutate(justification_for_sampling = stringr::str_replace_all(justification_for_sampling, "[\\,,\\.]", "<br>")) |> 
    dplyr::mutate(justification_for_sampling = gsub("((?:\\S+\\s+){6}\\S+)([ ,\\.])", "\\1<br>", justification_for_sampling, perl = TRUE))
,
className = 'hctf_popup_table')

# Pipette icon comes from this webpage: https://www.freeiconspng.com/img/31423
env_square_marker <-
  makeIcon(iconUrl = "utils/water-fountain.png",
           iconWidth = 18,
           iconHeight = 18,
           )

leaflet(width = '100%') |>
  addTiles(group = "OpenStreetMap") |>
  addProviderTiles(providers$CartoDB, group = "cartoDB") |>
  addLayersControl(position = 'bottomleft',
                   baseGroups = c("cartoDB","OpenStreetMap"),
                   overlayGroups = c('provincial parks',
                                     "wbs with sampling prop",
                                     "wbs without sampling prop",
                                     "sampling points",
                                     "ENV sampling points"),
                   options = layersControlOptions(collapsed = F)) |>
  leaflet::addMapPane(name = "parks", zIndex = 200) |>
  leaflet::addMapPane(name = "waterbodies", zIndex = 300) |>
  leaflet::addMapPane(name = "sampling_points", zIndex = 500) |>
  leaflet::addMapPane(name = "ENV_sampling_points", zIndex = 600) |>
  addPolygons(
    data = bc_parks,
    color = 'darkgreen',
    fill = 'darkgreen',
    fillOpacity = 0.5,
    weight = 1,
    label = ~stringr::str_to_title(PROTECTED_LANDS_NAME),
    group = 'provincial parks',
    options = pathOptions(pane = 'parks')
  ) |> 
  addPolygons(
    data = all_shortlist_lakes_w_props,
    weight = 2,
    color = ~props_pal(proposed_sampling),
    fillColor = ~props_pal(proposed_sampling),
    label = ~GNIS_NA,
    options = pathOptions(pane = "waterbodies"),
    group = 'wbs with sampling prop'
  ) |> 
  addPolygons(
    data = all_shortlist_lakes_wout_props,
    weight = 2,
    color = ~props_pal(proposed_sampling),
    fillColor = ~props_pal(proposed_sampling),
    label = ~GNIS_NA,
    options = pathOptions(pane = "waterbodies"),
    group = 'wbs without sampling prop'
  ) |> 
  addCircleMarkers(
    data = dat_sf,
    fillColor = ~my_pal(Group),
    color = 'black',
    fillOpacity = 0.75,
    weight = 1.5,
    label = ~lapply(dat_sf_tbls, htmltools::HTML),
    group = 'sampling points',
    options = pathOptions(pane = "sampling_points")
  ) |>
  addMarkers(
    data = menv_sampling,
    icon = env_square_marker,
    label = ~lake_name_ems_site_name,
    group = 'ENV sampling points',
    options = markerOptions(pane="ENV_sampling_points")
    # options = pathOptions(pane = "ENV_sampling_points")
  ) |>
  addLegend(title = "Organization", pal = my_pal, values = unique(dat_sf$Group)) |>
  addLegend(title = "Sampling Proposal", pal = props_pal, values = unique(all_shortlist_lakes_s$proposed_sampling)) |> 
  addLegend(title = "Provincial Parks", labels = 'Park/Protected Area', colors = 'darkgreen') |> 
  addScaleBar('bottomright') |>
  leaflet.extras::addResetMapButton() |> 
  leaflet.extras::addFullscreenControl(position = 'bottomright')
```

```{r}

```

